
services:
  - docker:dind

stages:
  - build

.build:
  image: docker:latest
  stage: build
  before_script:
    - apk update
    - apk add --no-cache docker-compose

include:
  - frontend/.gitlab-ci.yml
