
services:
  - docker:dind

stages:
  - lint
  - build_and_lint
  - test
  - build_and_test
  - build
  - apidoc

.lint:
  image: docker:latest
  stage: lint
  before_script:
    - apk update
    - apk add --no-cache docker-compose
  allow_failure: true
  only:
    refs:
      - main
    changes:
      - ./frontend/*
      - .gitlab-ci.yml
      - docker-compose.yml

.build_and_lint:
  image: docker:latest
  stage: build_and_lint
  before_script:
    - apk update
    - apk add --no-cache docker-compose
  when: on_failure
  only:
    refs:
      - main
    changes:
      - ./frontend/*
      - .gitlab-ci.yml
      - docker-compose.yml

.test:
  image: docker:latest
  stage: test
  before_script:
    - apk update
    - apk add --no-cache docker-compose
  allow_failure: true
  only:
    refs:
      - main
    changes:
      - ./frontend/*
      - .gitlab-ci.yml
      - docker-compose.yml

.build_and_test:
  image: docker:latest
  stage: build_and_test
  before_script:
    - apk update
    - apk add --no-cache docker-compose
  when: on_failure
  only:
    refs:
      - main
    changes:
      - ./frontend/*
      - .gitlab-ci.yml
      - docker-compose.yml

.build:
  image: docker:latest
  stage: build
  before_script:
    - apk update
    - apk add --no-cache docker-compose
  only:
    refs:
      - main
    changes:
      - ./frontend/*
      - .gitlab-ci.yml
      - docker-compose.yml

.apidoc:
  image: docker:latest
  stage: apidoc
  before_script:
    - apk update
    - apk add --no-cache docker-compose
  only:
    refs:
      - main
    changes:
      - ./frontend/*
      - .gitlab-ci.yml
      - docker-compose.yml

include:
  - frontend/.gitlab-ci.yml
