version: "3.9"
services:
  frontend:
    image: registry.gitlab.com/haapsee/mean-template/frontend:development
    build:
      context: ./frontend
      target: development
      dockerfile: Dockerfile
    environment:
      - CHROME_BIN=/usr/bin/chromium-browser
    ports:
      - "4200:4200"
