
name: "frontend"

on:
  workflow_dispatch:
    inputs:
      newUnityVersion:
        description: 'The new version number string to generate the license activation file for.'
        required: true
jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [17.x]
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - run: npm run test
